"""credit hours dield added to course table

Revision ID: 2ce34f8ffbba
Revises: 0aa11d573e65
Create Date: 2023-03-07 15:16:14.971676

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ce34f8ffbba'
down_revision = '0aa11d573e65'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('credit_hours', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.drop_column('credit_hours')

    # ### end Alembic commands ###
